[build]
  Functions = "functions"
  command = "npm run build"
  publish = "dist"
  NODE_ENV = "8.9.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[[redirects]]
  from = "/new"
  to = "/login"
  status = 401
  force = true
  conditions = {Role = ["admin"]}

